### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by jgoldhammer** [wilkinsona/rest-documentation#6]
Hi,

I like this idea, but it seems development has stopped. Any plans to bring it back to spring boot?

Thanks,
Jens

**Comment by wilkinsona** [comment]
No plans to bring the idea back to Boot as it proved to be rather flawed. It did, however, lead to the creation of [Spring REST Docs](https://github.com/spring-projects/spring-restdocs). I've updated the README.

**Comment by jgoldhammer** [comment]
Thanks for the info. Is it possible to serve Spring Rest documentation in spring boot like Swagger in Jhipster? So that the application itself hosts the documentation??

Thanks,
Jens

**Comment by wilkinsona** [comment]
Yes. The documentation describes how to do it with either [Maven](http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#getting-started-build-configuration-maven-packaging) or [Gradle](http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#getting-started-build-configuration-gradle-packaging-the-documentation).
